/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bankmanage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Random;
import javax.swing.JOptionPane;
import java.util.*;
import javax.mail.*;
import javax.mail.internet.*;
import javax.activation.*;





/**
 *
 * @author Acer
 */
public class fpass extends javax.swing.JFrame {
 Connection conn;
ResultSet rs;
PreparedStatement pat;
Statement st;
String txt;
String pass;
String id3x;


    /**
     * Creates new form fpass
     */
    public void Randomotp(){
        Random ra=new Random();
        txt=String.valueOf(ra.nextInt(100000+1));
        
    }
    public fpass() {
        initComponents();
        pass_in.setToolTipText("Enter Password");
        disp.setVisible(false);
    }
    public void takeinput(){
    pass_in.getText();
    con_in.getText();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        otp_in = new javax.swing.JTextField();
        acc_in = new javax.swing.JTextField();
        pass_in = new javax.swing.JPasswordField();
        con_in = new javax.swing.JPasswordField();
        rSButton1 = new rojeru_san.RSButton();
        rSButton2 = new rojeru_san.RSButton();
        rSButton3 = new rojeru_san.RSButton();
        jLabel14 = new javax.swing.JLabel();
        rSButton4 = new rojeru_san.RSButton();
        disp = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankmanage/imgs/white.png"))); // NOI18N
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 0, -1, 136));

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ROYCE BANK'S");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 53, -1, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 160));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel9.setText("Account Number:");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("Forget Password");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel12.setText("New Password:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel13.setText("Enter Verification Code:");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        otp_in.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel4.add(otp_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 294, 41));
        jPanel4.add(acc_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 294, 38));
        jPanel4.add(pass_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 294, 42));
        jPanel4.add(con_in, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 294, 42));

        rSButton1.setBackground(new java.awt.Color(204, 0, 0));
        rSButton1.setText("Send Code");
        rSButton1.setColorHover(new java.awt.Color(255, 102, 102));
        rSButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rSButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(rSButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 140, -1));

        rSButton2.setBackground(new java.awt.Color(204, 0, 0));
        rSButton2.setText("Clear");
        rSButton2.setColorHover(new java.awt.Color(255, 102, 102));
        rSButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rSButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(rSButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 118, -1));

        rSButton3.setBackground(new java.awt.Color(204, 0, 0));
        rSButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bankmanage/imgs/back-icon.png"))); // NOI18N
        rSButton3.setText(" Back");
        rSButton3.setColorHover(new java.awt.Color(255, 102, 102));
        rSButton3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        rSButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(rSButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 130, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel14.setText("Confirm Password:");
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        rSButton4.setBackground(new java.awt.Color(204, 0, 0));
        rSButton4.setText("Submit");
        rSButton4.setColorHover(new java.awt.Color(255, 102, 102));
        rSButton4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        rSButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(rSButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 118, -1));

        disp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        disp.setText("xxx");
        jPanel4.add(disp, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 180, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 650, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        mylogin lg=new mylogin();
        lg.setVisible(true);
    }//GEN-LAST:event_rSButton3ActionPerformed

    private void rSButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton2ActionPerformed
        // TODO add your handling code here:
        acc_in.setText("");
        //name_in.setText("");
        // phone_in.setText("");
        pass_in.setText("");
        con_in.setText("");
    }//GEN-LAST:event_rSButton2ActionPerformed

    private void rSButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton1ActionPerformed
        // TODO add your handling code here:
        String from="bhoitesumit4@gmail.com";
        String email;
        String host="localhost";
        int tempx=0;
        int tempxx=0;
        
        String cpass;
        String acc;
        pass=pass_in.getText();
        cpass=con_in.getText();
        acc=acc_in.getText();
        if(pass.equals(cpass))
        {
            tempx++;
            int temp=0;
        String sql="Select * from account";
        //String acc_no=jTextField3.getText();
       // String pass=jPasswordField1.getText();
    
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost:3307/bank?serverTimezone=UTC","root","");
            st=conn.createStatement();
            rs=st.executeQuery(sql);
            while(rs.next()){
                String acc_check=rs.getString("Account_no");
               // String pass_check=rs.getString("Password");
                String namexx=rs.getString("Name");
                String idxx=rs.getString("id");
                email=rs.getString("Email_id");
                if((acc.equals(acc_check))){
                    id3x=idxx;
                    disp.setVisible(true);
                    disp.setText("Password Matched!");
                    tempxx++;
                    Randomotp();
                   // JOptionPane.showMessageDialog(this,txt);
                  // System.out.println(txt);
                  Properties p=new Properties();                    
                    p.put("mail.smtp.auth","true");
                    p.put("mail.smtp.starttls.enable","true");
                    p.put("mail.smtp.host","smtp.gmail.com");
                    p.put("mail.smtp.port","587");
                    Session s = Session.getDefaultInstance(p, new javax.mail.Authenticator() {
                        protected PasswordAuthentication getPasswordAuthentication()
                        {
                            return new PasswordAuthentication("bhoitesumit4@gmail.com","sumit2002");
                        } 
                    });
                    try{
                        MimeMessage m = new MimeMessage(s);
                        m.setFrom(from);
                        m.addRecipient(Message.RecipientType.TO, new InternetAddress(email));
                        m.setSubject("Royce Banks - Forget Password !!!");
                        m.setText("Dear "+namexx+" as per your Forget Password request,\nYour OTP="+txt);
                        Transport.send(m);
                        JOptionPane.showMessageDialog(this,"Please check your Mail !");
                        rSButton1.setVisible(false);
                        acc_in.setEditable(false);
                        pass_in.setEditable(false);
                        con_in.setEditable(false);
                        
                        
                        
                        
                    
                    }catch(Exception e){
                     e.printStackTrace();
                    }

                    }
                
            }
//            if(temp==0){
//                
//            }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"Login Failed!");
            
        }
        }
        if(tempx==0){
            disp.setText("Not Matched");
        }
        if(tempxx==0){
            JOptionPane.showMessageDialog(this,"Enter Correct Details!");
        }
    }//GEN-LAST:event_rSButton1ActionPerformed

    private void rSButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButton4ActionPerformed
        // TODO add your handling code here:
        String otpx=otp_in.getText();
                        int tem=0;
        try{
//                        System.out.println(otpx);
//                        System.out.println(txt);
                        if(otpx.equals(txt)){
                            tem++;
                             Class.forName("com.mysql.cj.jdbc.Driver");
                             conn = DriverManager.getConnection("jdbc:mysql://localhost:3307/bank?serverTimezone=UTC","root","");
//                             System.out.println(pass);
//                             System.out.println(id3x);
                             String sqq=("UPDATE account SET Password='"+pass+"' Where id ="+id3x); 
                             pat=conn.prepareStatement(sqq);
                             pat.executeUpdate(sqq);
                             String sqlx=("UPDATE account SET Confirm='"+pass+"' Where id ="+id3x);
                             pat=conn.prepareStatement(sqlx);
                             pat.executeUpdate(sqlx);
                                    JOptionPane.showMessageDialog(this,"Password Changed Successfully");
                                    mylogin ml=new mylogin();
                                    ml.setVisible(true);
                                    this.dispose();
                        }
                        if(tem==0){
                          JOptionPane.showMessageDialog(this,"Invalid OTP!");  
                        }
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_rSButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fpass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fpass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acc_in;
    private javax.swing.JPasswordField con_in;
    private javax.swing.JLabel disp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField otp_in;
    private javax.swing.JPasswordField pass_in;
    private rojeru_san.RSButton rSButton1;
    private rojeru_san.RSButton rSButton2;
    private rojeru_san.RSButton rSButton3;
    private rojeru_san.RSButton rSButton4;
    // End of variables declaration//GEN-END:variables
}
